core/models.py
import datetime
from django.db import models
from django.utils.translation import gettext as _
from accounts.models import UserProfile
from django.db.models.manager import Manager
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
#from tagging_autocomplete_tagit.models import TagAutocompleteTagItField

class Question(models.Model):
	question = models.CharField(max_length = 250)
	date = models.DateField(default=datetime.date.today)
	submitter = models.ForeignKey(UserProfile, null=True, blank=True, default=None, related_name='submissions')
	answered_by = models.ManyToManyField(UserProfile, null=True, blank=True, default=None, related_name = 'answered')
	slug = models.SlugField(max_length = 250, blank = True, null=True)
	#tags = TagAutocompleteTagItField(max_tags=False)
	
	class Meta:
		ordering = ['-date']
		verbose_name = _('question')
		verbose_name_plural = _('questions')
		
	def __unicode__(self):
		return self.question
		
	def get_vote_count(self):
		return Vote.objects.filter(question=self).count()
	vote_count = property(fget=get_vote_count)
		
	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.question)
		super(Question, self).save(*args, **kwargs)


class Answer(models.Model):
	question = models.ForeignKey(Question)
	answer = models.CharField(max_length = 250)
	selected_by = models.ManyToManyField(UserProfile, null=True, blank=True, default=None, related_name = 'selection')

	class Meta:
		verbose_name = _('answer')
		verbose_name_plural = _('answers')

	def __unicode__(self):
		return u'%s' % (self.answer,)

	def get_vote_count(self):
		return Vote.objects.filter(answer=self).count()

	def get_vote_count_male(self):
		return self.selected_by.filter(gender="male").count()

	def get_vote_count_female(self):
		return self.selected_by.filter(gender="female").count()

	vote_count = property(fget=get_vote_count)
	vote_count_male = property(fget=get_vote_count_male)
	vote_count_female = property(fget=get_vote_count_female)

class Vote(models.Model):
	question = models.ForeignKey(Question)
	answer = models.ForeignKey(Answer)
	ip = models.IPAddressField(verbose_name=_('user\'s IP'))
	users = models.ManyToManyField(UserProfile)
	datetime = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = _('vote')
		verbose_name_plural = _('votes')

core/templates/current_question.html
<script type="text/javascript">
$(document).ready(function() {
  pageurl = '/'+'{{current_question.slug}}'+',' + '{{current_question.id}}' + '/';
  window.history.pushState({path:pageurl},'',pageurl);
});
google.load("visualization", "1", { packages: ["corechart"] });
    $('.answer').click(function() {
      $('#previous_question').fadeOut(300);
      $('#current_question').fadeOut(300);
        $.ajax({
          url: '/vote/' + this.id + "/",
          success: function(data) {
            $('#previous_question').fadeOut(300);
            $('#current_question').html('&nbsp;').load('/current_question/' + data.current_question_pk + "/");
            $('#current_question').fadeIn(300);
            $('#previous_question').html('&nbsp;').load('/previous_question/' + data.previous_question_pk + "/");
            $("#previous_question").fadeIn(300);
          }
        });
    return false;
    });

 </script>


<div id="current_question" class="row">
  <div class="twelve columns">
    <div class="panel red">
      <div class="row">
        <div class="twelve columns">
          <p class="current_question text-center">{{current_question.question}}</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="current_answers" class="row">
  <div class="twelve columns">
    <div class="panel blue">
      <div class="row">
        <div class="twelve columns">
          {% for a in current_question.answer_set.all %} {% csrf_token %}
          <a href = '' id="{{a.id}}" type="int" class="answer"><p class="current_answers text-center">{{a.answer}}</p></a>
          {%endfor%}
        </div>
      </div>
    </div>
  </div>
</div>

<div id = "previous_question"></div>

core/templates/index.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>QNA</title>
{%load staticfiles%}
<link href="{% static 'app.css' %}" rel="stylesheet" type="text/css" />
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>

</head>

<body>
{% load url from future %}

<p><a rel="nofollow" href="{% url "socialauth_begin" "facebook" %}">{{ "facebook"|title }}</a>{% csrf_token %}</p>
<p><a href = "{% url 'core.views.questions' %}">Proceed anonymously</a></p>
</div>
<div id="landing-box-clear">
<p style="font-size: 4.5em; font-family: impact;">INSERT LOGO</p>
<p>The monotony of test-taking with the bonus of irrelevance.</p>
</div>
<!-- End ofcontent -->
</div>

<div id="landing-bottom">
<p>Copyright gibberish.</p>
</div>

</div>
</body>

</html>

core/templates/navbar.html
<div class="container">
    <div class="header">
        <a class="brand">QNA</a>
        <form class="search pull-right">
            <input type="text" class="search-query" placeholder="Search...">
        </form>
        <ul class="nav pull-right">
            <li>
                <a href="#">Submit</a>
            </li>
            <li>
                <a href="#">Profile</a>
            </li>
            <li>
                <a href="#">Login</a>
            </li>
        </ul>
    </div>
</div>

core/templates/previous_question.html
<div id="previous_question" class="row">
  <div class="twelve columns">
    <div class="panel gray">
      <div class="row">
        <div class="twelve columns">
          <p class="previous_question text-center">{{previous_question.question}}</p>
        </div>
      </div>
      <div class="row">
          <div class="eight columns centered">
          <div id="visualization"></div>
          </div>
      </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="http://www.google.com/jsapi"></script>

<script type="text/javascript">
  $(document).ready(function() {
    google.load("visualization", "1", { packages: ["corechart"] });
    var chartdata;
    chartdata = [
    ['Answer', 'Votes'],
    {%for answer in previous_question.answer_set.all %}
    ['{{answer.answer}}', {{answer.get_vote_count}}],
    {% endfor %}
    ];
    var datatable = google.visualization.arrayToDataTable(chartdata);
    chart = new google.visualization.PieChart(document.getElementById('visualization'));
    options = {
      'backgroundColor': "transparent",
      'colors': ['#f15c22', '#eb4f68', '#eb62ca', '#9567eb', '#73a1d5'],
      'sliceVisibilityThreshold':0,
      'chartArea': {'width':"100%",'height':"80%"},
      'legend': {'position': 'bottom'}
    };
    chart.draw(datatable, options);
  });
 </script>

core/templates/profile.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />
  <title>QNA</title>

  <!-- Include Font Files -->
  <link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>

  <!-- Include CSS Files -->
  {% load staticfiles %}
  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" type="text/css" />
  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
  <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">


</head>

<body>

<div class="row">
  <div class="twelve columns">
  <nav class="top-bar">
    <ul>
      <li class="name"><h1><a href="{%url index%}">QNA</a></h1></li>
      <li class="toggle-topbar"><a href="#"></a></li>
    </ul>
    <section>
      <ul class="right">
        <li><a href="/submitquestion/">SUBMIT</a></li>
        <li><a href="/profile/">PROFILE</a></li>
        <li><a href="#">{% if user.is_authenticated %} LOGGED IN AS {{user.first_name}} {{user.last_name}}. {%else%} LOGIN {%endif%}</a></li>
        <li class="search">
          <form>
            <input id="search" type="search" class="search-query" placeholder="Search..." />
          </form>
        </li>
      </ul>
    </section>
  </nav>
  </div>
</div>
<div id="submitquestion"></div>

<div id="search_results"></div>
<!--PROFILE BEGINS HERE-->

<div id="current_question" class="row">
  <div class="twelve columns">
    <div class="panel red">
      <div class="row">
        <div class="twelve columns">
          <h1>{{user.first_name}} {{user.last_name}}</h1>
        </div>
      </div>
      <!-- Stats -->
        <div class="row">
          <h3 class="four columns">STATS</h3>
          <div class="eight columns h3_offset">
          <p>Member Since: {{user.userprofile.created_at}}</p>
          <p>Age: {{user.userprofile.age}}</p>
          <p>Gender: {{user.userprofile.gender}}</p>
          <p># of Friends: {{user.userprofile.friends.count}}</p>
          <p>Friend List: </p>
          {%for friend in user.userprofile.friends.all %}
          <p>{{friend.first_name}}</p></br>
          {%endfor%}
          <p>Favorite Subject: {{user.userprofile.toptag}}</p>
          </div>    
        </div>
      <!-- End Stats -->
      <!-- Questions Submitted -->
        <div class="row">
          <div class="four columns">
            <h3>SUBMITTED</h3>
          </div>
          <div class="eight columns h3_offset">
            <p>{{totalvotes}} people have answered your questions at a rate of {{user.submittedresponserate}} per day.</p>
            <p>{{user.userprofile.submittedresponsesrank}} users have asked more questions than you.</p>
            <p class="expanderHead">Questions Submitted ({{user.userprofile.submissions.count}}) <span class="right expanderSign">+</span></p>
            <div class="expanderContent">
            <!-- Begin Insert of User-Submitted Questions -->
            {%for question in user.userprofile.submissions.all %}
            Question:{{question.question}}<br/>
            Answers: <br>
            {% for answer in question.answer_set.all %}
            {{answer}} : {{answer.get_vote_count}} votes <br>
            {%endfor%}  
            {%endfor%}
            <!-- End Insert of User-Submitted Questions -->
            </div>
          </div>    
        </div>
      <!-- End Questions Submitted -->
      <!-- Questions Answered -->
        <div class="row">
          <div class="four columns">
            <h3>ANSWERED</h3>
          </div>
          <div class="eight columns h3_offset">
            <p>You have answered {{user.userprofile.selection.count}} questions at a rate of {{user.answeredresponserate}} per day.</p>
            <p>{{user.answeredresponsesrank}} users have answered more questions than you.</p>
            <p class="expanderHead2">Questions Answered ({{user.userprofile.selection.count}}) <span class="right expanderSign">+</span></p>
            <div class="expanderContent2">
            <!-- Begin Insert of User-Submitted Answers -->
			{% for answer in user.userprofile.selection.all %}
			Answer: {{answer}}<br>
			Question: {{answer.question}}<br>
			{%endfor%}
            <!-- End Insert of User-Submitted Answers -->
            </div>
          </div>    
        </div>
      <!-- End Questions Answered -->
    </div>
  </div>
</div>
<div id = "current_question"></div>
<div id="previous_question"></div>

    <script type="text/javascript">
  google.load("visualization", "1", { packages: ["corechart"] });
  $(document).ready(function() {
    $('.answer').bind('click', function() {
        $('#previous_question','#current_question').fadeOut(300);
        $.ajax({
          url: '/vote/' + this.id + "/",
          success: function(data) {
            Change(data.previousanswers);
            $('#current_question').html('&nbsp;').load('/current_question/' + data.current_question_pk + "/");
            $('#current_question').fadeIn(300);
            $('#previous_question').html('&nbsp;').load('/previous_question/' + data.previous_question_pk + "/");
            $('#previous_question').fadeIn(300);
          }
        });

    });
  });
</script>
<!-- DO NOT CHANGE. The order matters for the autocomplete to work with foundation -->
  <script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
  <script src="{% static 'javascripts/jquery.js' %}"></script>
  <script src="{% static 'javascripts/foundation.min.js' %}"></script>
  <script src="{% static 'javascripts/app.js' %}"></script>
  <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
  <script type = "text/javascript">

    $(function() {

      $.ui.autocomplete.prototype._renderItem = function(ul, item) {
        return $("<li></li>").data("item.autocomplete", item).append($("<a></a>").html(item.label)).appendTo(ul);
      };

      $("#search").autocomplete({
        source: function(request, response) {
          var pavdude = request.term;
          $.ajax({
            url: "{% url search %}?searchtext=" + request.term,
            type: "GET",
            success: function(data) {
              response($.map(data, function(item) {
                return {
                  label: item.fields.question,
                  value: item.pk
                }
              }));
            },
            data: request.term,
            dataType: "json"
          });
          var searchtext = request.term;
        },

        response: function(event, ui) {
          ui.content.push({
            label:  "<b>Show All Search Results</b>",
            value: ui
          });
          ui.content.push({
            label:  "<b>Submit New Question</b>",
            value: ui
          });
        },
        select: function(event, ui) {
          event.preventDefault()
          if (ui.item.label == "<b>Show All Search Results</b>")
          {
            var searchtext = $("#search").val();
            $('#previous_question').fadeOut(300);
            $('#current_question').fadeOut(300);
            $('#search_results').html('&nbsp;').load('/search_results/'+searchtext+"/");
          }
          else if (ui.item.label == "<b>Submit New Question</b>")
            {
              $('#previous_question').fadeOut(300);
              $('#current_question').fadeOut(300);
              window.open("/submitquestion/","_self");
            }
          else
          {
            var url = "/current_question/" + ui.item.value;
            $('#previous_question').fadeOut(300);
            $('#current_question').delay(200).fadeOut(300);
            $('#current_question').html('&nbsp;').load(url);
            $('#current_question').fadeIn(300);
            $('#previous_question').fadeIn(300);
          };
        }
      })
    });

</script>
  <!-- Initialize JS Plugins -->
  <script src="{% static 'javascripts/app.js'%}"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".expanderHead").click(function(){
        $(".expanderContent").slideToggle();
        if ($(".expanderSign").text() == "+"){
          $(".expanderSign").html("−")
        }
        else {
          $(".expanderSign").text("+")
        }
      });
    });
  </script>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".expanderHead2").click(function(){
        $(".expanderContent2").slideToggle();
        if ($(".expanderSign").text() == "+"){
          $(".expanderSign").html("−")
        }
        else {
          $(".expanderSign").text("+")
        }
      });
    });
  </script>


</body>
</html>

core/templates/questions.html
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />
  <title>QNA</title>

  <!-- Include Font Files -->
  <link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>

  <!-- Include CSS Files -->
  {% load staticfiles %}
  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" type="text/css" />
  <link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
  <link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">
</head>

<body>

<div class="row">
  <div class="twelve columns">
  <nav class="top-bar">
    <ul>
      <li class="name"><h1><a href="{%url index%}">QNA</a></h1></li>
      <li class="toggle-topbar"><a href="#"></a></li>
    </ul>
    <section>
      <ul class="right">
        <li><a href="/submitquestion/">SUBMIT</a></li>
        <li><a href="/profile/">PROFILE</a></li>
        <li><a href="#">{% if user.is_authenticated %} LOGGED IN AS {{user.first_name}} {{user.last_name}}. {%else%} LOGIN {%endif%}</a></li>
        <li class="search">
          <form>
            <input id="search" type="search" class="search-query" placeholder="Search..." />
          </form>
        </li>
      </ul>
    </section>
  </nav>
  </div>
</div>

<div id="submitquestion"></div>

<div id="search_results"></div>

<div id="current_question"></div>

<div id="previous_question"></div>

{# --------- LOAD JQUERY AND GOOGLE CHART API -------------#}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.js"></script>
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", { packages: ["corechart"] });
  $(document).ready(function() {
    {% if current_question %}
    $('#current_question').html('&nbsp;').load('/current_question/' + {{current_question.id}} + "/");
    {% endif %}
    $('.answer').bind('click', function() {
        $('#previous_question','#current_question').fadeOut(300);
        $.ajax({
          url: '/vote/' + this.id + "/",
          success: function(data) {
            Change(data.previousanswers);
            $('#current_question').html('&nbsp;').load('/current_question/' + data.current_question_pk + "/");
            $('#current_question').fadeIn(300);
            $('#previous_question').html('&nbsp;').load('/previous_question/' + data.previous_question_pk + "/");
            $('#previous_question').fadeIn(300);
          }
        });

    });
  });
</script>


  <!-- Included JS Files (Uncompressed) -->
  <!--
  <script src="javascripts/jquery.js"></script><script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script><script src="javascripts/jquery.foundation.forms.js"></script><script src="javascripts/jquery.foundation.reveal.js"></script><script src="javascripts/jquery.foundation.orbit.js"></script><script src="javascripts/jquery.foundation.navigation.js"></script><script src="javascripts/jquery.foundation.buttons.js"></script><script src="javascripts/jquery.foundation.tabs.js"></script><script src="javascripts/jquery.foundation.tooltips.js"></script><script src="javascripts/jquery.foundation.accordion.js"></script><script src="javascripts/jquery.placeholder.js"></script><script src="javascripts/jquery.foundation.alerts.js"></script><script src="javascripts/jquery.foundation.topbar.js"></script><script src="javascripts/jquery.foundation.joyride.js"></script><script src="javascripts/jquery.foundation.clearing.js"></script><script src="javascripts/jquery.foundation.magellan.js"></script>
  -->
  
  <!-- Included JS Files (Compressed) -->

  <!-- DO NOT CHANGE. The order matters for the autocomplete to work with foundation -->
  <script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
  <script src="{% static 'javascripts/jquery.js' %}"></script>
  <script src="{% static 'javascripts/foundation.min.js' %}"></script>
  <script src="{% static 'javascripts/app.js' %}"></script>
  <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
  <script type = "text/javascript">

    $(function() {

      $.ui.autocomplete.prototype._renderItem = function(ul, item) {
        return $("<li></li>").data("item.autocomplete", item).append($("<a></a>").html(item.label)).appendTo(ul);
      };

      $("#search").autocomplete({
        source: function(request, response) {
          var pavdude = request.term;
          $.ajax({
            url: "{% url search %}?searchtext=" + request.term,
            type: "GET",
            success: function(data) {

              response($.map(data, function(item) {
                data.slice(0,6);
                return {
                  label: item.fields.question,
                  value: item.pk
                }
              }));
            },
            data: request.term,
            dataType: "json"
          });
          var searchtext = request.term;
          response(results.slice(0,6));
        },

        response: function(event, ui) {
          ui.content.push({
            label:  "<b>Show All Search Results</b>",
            value: ui
          });
          ui.content.push({
            label:  "<b>Submit New Question</b>",
            value: ui
          });
        },
        select: function(event, ui) {
          event.preventDefault()
          if (ui.item.label == "<b>Show All Search Results</b>")
          {
            var searchtext = $("#search").val();
            $('#previous_question').fadeOut(300);
            $('#current_question').fadeOut(300);
            $('#search_results').html('&nbsp;').load('/search_results/'+searchtext+"/");
          }
          else if (ui.item.label == "<b>Submit New Question</b>")
            {
              $('#previous_question').fadeOut(300);
              $('#current_question').fadeOut(300);
              window.open("/submitquestion/","_self");
            }
          else
          {
            var url = "/current_question/" + ui.item.value;
            $('#previous_question').fadeOut(300);
            $('#current_question').delay(200).fadeOut(300);
            $('#current_question').html('&nbsp;').load(url);
            $('#current_question').fadeIn(300);
            $('#previous_question').fadeIn(300);
          };
        }
      })
    });

</script>


</body>
</html>

core/templates/search_form.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title></title>
	<link rel="stylesheet" href="http://jqueryui.com/themes/base/jquery.ui.all.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
	 <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
<script>
  $(document).ready(function() {
          $("#search").autocomplete({
              source: function (request, response) {
                $.ajax({
                      url: "{% url search %}?searchtext="  + request.term,
                      type: "GET",
                      success: function (data) {
                        console.log(data);
                          response($.map(data, function (item) {
                              return {
                                  label: item.fields.question,
                                  value: item.pk
                            }
                          }));
                      },
                      data: request.term,
                      dataType: "json"
                  }); 
              },
             select: function(event, ui) {
              console.log(ui);
              var url = "/current_question/"+ui.item.value;
               $('#previous_question').fadeOut(300);
              $('#current_question').delay(200).fadeOut(300);
                      $('#current_question').html('&nbsp;').load(url);
        $('#current_question').fadeIn(300);
        $('#previous_question').fadeIn(300);
            
             }
          });
  });
  </script>
</head>
<body>
	<div class = "ui-widget">
	<label for="search">Search: </label>
	<input id="search" value ="search"/>
</div>
</body></html>

core/templates/search_form2.html
<html>

<body>
	
	{% if entered %}
		<p>You entered: <blockquote>{{ entered }}</blockquote></p>
	{% endif %}
	
	<form action="{% url search_form %}" method="GET">
	<table>
	{{ form }}
	<tr>
		<th></th><td><input type="submit" /></td>
	</tr>
	</table>
	</form>
	
</body>
</html>

core/templates/search_results.html
{% for q in results %}
<style type="text/css">
p {color:black;}
</style>
<p>{{q}}</p>
{%endfor%}

core/templates/submit.html
PLACEHOLDER FOR SUBMISSION PAGE

core/templates/test.html
<!doctype html>
 
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>jQuery UI Autocomplete - Custom data and display</title>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css" />
    <style>
    #project-label {
        display: block;
        font-weight: bold;
        margin-bottom: 1em;
    }
    #project-icon {
        float: left;
        height: 32px;
        width: 32px;
    }
    #project-description {
        margin: 0;
        padding: 0;
    }
    </style>
    <script>
    $(function() {
        var projects = [
            {
                value: "jquery",
                label: "jQuery",
                desc: "the write less, do more, JavaScript library",
                icon: "jquery_32x32.png"
            },
            {
                value: "jquery-ui",
                label: "jQuery UI",
                desc: "the official user interface library for jQuery",
                icon: "jqueryui_32x32.png"
            },
            {
                value: "sizzlejs",
                label: "Sizzle JS",
                desc: "a pure-JavaScript CSS selector engine",
                icon: "sizzlejs_32x32.png"
            }
        ];
 
        $( "#project" ).autocomplete({
            minLength: 0,
            source: projects,
            focus: function( event, ui ) {
                $( "#project" ).val( ui.item.label );
                
                return false;
            },
            select: function( event, ui ) {
                $( "#project" ).val( ui.item.label );
                $( "#project-id" ).val( ui.item.value );
                $( "#project-description" ).html( ui.item.desc );
                $( "#project-icon" ).attr( "src", "images/" + ui.item.icon );
                $( '#static-text').html("static text");
                return false;
                
            }
        })
        .data( "autocomplete" )._renderItem = function( ul, item ) {
            return $( "<li>" )
                .data( "item.autocomplete", item )
                .append( "<a>" + item.label + "<br>" + item.desc + "</a>" )
                .appendTo( ul );
        };
    });
    </script>
</head>
<body>
 
<div id="project-label">Select a project (type "j" for a start):</div>
<img id="project-icon" src="images/transparent_1x1.png" class="ui-state-default" alt="" />
<input id="project"/ >
<input type="hidden" id="project-id" />
<p id="project-description"></p>
<p id ="static-text"></p>

 
 
</body>
</html>